### ISSUE TITLE
Position sticky on team planner header

### ISSUE THREAD

**Issue by lucasyoungers** [richi3f/pokemon-team-planner#19]
I love the team planner, but I've noticed that (not sure how recently) the team display header is now position sticky. I wouldn't mind if the header shrunk when it hit the top of the screen, but at the moment it takes up a good half the screen and makes scrolling through options pretty unbearable.

I would propose either the easy option, which is just removing position: sticky from the header, or the slightly more involved option, which is shrinking to an icon or small image view when the page is scrolled.

I'm more than willing to make these changes, provided I get the okay. Thanks for providing the community for such a great tool!

**Comment by richi3f** [comment]
Hi there! That sounds like a good idea. If you can do the automatic shrinking, that would be great. Feel free to submit a pull request when you're ready. :)
