### ISSUE TITLE
Misc Forms Not Showing Up on Home

### ISSUE THREAD

**Issue by AzureTheEgg** [richi3f/pokemon-team-planner#24]

**Comment by richi3f** [comment]
Hello. The forms are showing up in the Pokémon HOME planner. They are hidden by default, but you have enable them by selecting the "Misc. Forms" filter:

![screenshot](https://user-images.githubusercontent.com/93887491/193525535-79c66f47-4c00-4fc9-97e6-28c92c30d4a8.png)
