### ISSUE TITLE
Drapion is too small

### ISSUE THREAD

**Issue by ghost** [richi3f/pokemon-team-planner#28]
Hey, I've noticed is just too small compared to the others. I mean, in terms of sprite obviously. Pls change it! ps I love your work

**Comment by richi3f** [comment]
Hi there.

The images are taken directly from Pokémon HOME data, and they keep the same scale used there. Although the size of Drapion can be easily "fixed," I prefer not to do any special treatment to specific Pokémon. That makes maintenance easier for me. Hope you understand.
