### ISSUE TITLE
Feedback Teamplanner

### ISSUE THREAD

**Issue by Tiffoes** [richi3f/pokemon-team-planner#37]
Love the site, use it often to try and build teams that work well or look good together. Really wish every generation was uploaded into ''Home'' instead of having the Scarlet/Violet mons seperate. It would be really nice if we could pre-plan teams before Home gets implemented to Scarlet/Violet.

**Comment by richi3f** [comment]
Hey there, sorry for the belayed response. Unfortunately, there is no consistent art resources for gen 9 Pokémon and old Pokémon (e.g., I'm using HOME sprites for the rest of the site except the SV dex), so atm I am holding out on updating until the HOME update brings the same art style for all Pokémon.
