### ISSUE TITLE
Z-moves?

### ISSUE THREAD

**Issue by Joakingolder** [richi3f/pokemon-team-planner#43]
I see that I can choose teratype in Scarlet and Violet, and in the other games I can choose megaevolution, G-maxs and other alternative forms, even in Home I can choose a team when Home is not a playable game because is a storage boxes of Pokémon.

But my question is if in Sun, Moon, UltraSun and UltraMoon I could choose Z-moves. I feel bad because Z-moves and Z-crystals are excluded from this.

**Comment by richi3f** [comment]
Moves are out of the scope of this planner, so Z-moves are not selectable. Unfortunately, I do not have the bandwidth or plans to change this anytime soon.
