### ISSUE TITLE
Pokemon Home Render of Paldean roster is out

### ISSUE THREAD

**Issue by aditwi05** [richi3f/pokemon-team-planner#47]
Source: Pokemon Data Miner
https://twitter.com/mattyoukhana_/status/1663359596860174336
![image](https://github.com/richi3f/pokemon-team-planner/assets/109051104/2c875069-e8e0-48ff-bf8d-8ca6d685fa4b)

**Comment by richi3f** [comment]
Handled by the latest update 😁 !
