### ISSUE TITLE
Request to exclude monotypes?

### ISSUE THREAD

**Issue by TBTH420** [richi3f/pokemon-team-planner#57]
I'm really sorry if this has been asked before, I was just wondering if we could have a toggle, maybe in the "exclude type" to exclude monotype pokemon, so only those with two types will show up?

**Comment by A-b-e-l** [comment]
It was included three times in[ this issue](https://github.com/richi3f/pokemon-team-planner/issues/38). Hopefully it makes it in as an actual feature!

**Comment by TBTH420** [comment]
I'm really sorry for repeating this!! I'm really new to Github and wasn't sure how posts work so I didn't check the others.

**Comment by A-b-e-l** [comment]
I think you should reopen this, as it's specifically related and not just under a seemingly feedback post.

**Comment by A-b-e-l** [comment]
Since it doesn't seem like you're reopening this, I will make an issue about it.
