### ISSUE TITLE
Modify the filters "evolution" and "generations" together in Home

### ISSUE THREAD

**Issue by Joakingolder** [richi3f/pokemon-team-planner#71]
Could you modify the filters "evolution - not fully evolved" and "generations".

I mean, if you select "not fully evolved" but you don't select "9th generation", could show Dunsparce or Girafarig, because the generation where they evolve is unmarked.

**Comment by richi3f** [comment]
In each game's individual planner, it already works like that. For instance, in the GSC planner, Dunsparce and Girafarig are counted as fully-evolved. I think the edit you suggest would get easily get confusing, so my suggestion is to use the planners for each game.
